### ISSUE TITLE
A typo in one of the imports keeps the tool from running

### ISSUE THREAD

**Issue by ewilded** [codingo/VHostScan#107]
## An attempt to run the tool after installation fails:

```
$ VHostScan

Traceback (most recent call last):
  File "/usr/local/bin/VHostScan", line 11, in <module>
    load_entry_point('VHostScan==1.21', 'console_scripts', 'VHostScan')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/VHostScan-1.21-py2.7.egg/VHostScan/VHostScan.py", line 8, in <module>
    from .lib.core.virtual_host_soutput_helpercanner import virtual_host_scanner
ImportError: No module named virtual_host_soutput_helpercanner
```

## Reason: VHostScan.py, line 8:
`from .lib.core.virtual_host_soutput_helpercanner import virtual_host_scanner`

## Do you have an idea for a solution?
Seems like the "output_helper" string crept into the class name.
Replacing the line with `from .lib.core.virtual_host_scanner import virtual_host_scanner` fixes the problem.

**Comment by codingo** [comment]
Closed with #108
