### ISSUE TITLE
DNS query issues

### ISSUE THREAD

**Issue by timkent** [codingo/VHostScan#68]
Scanning an IP resulted in this:

```
[+] Starting virtual host scan for 1.2.3.4 using port 80 and stdin, wordlists: 
[>] Ignoring HTTP codes: 404
Traceback (most recent call last):
  File "VHostScan.py", line 117, in <module>
    main()
  File "VHostScan.py", line 90, in main
    for ip in Resolver().query(arguments.target_hosts, 'A'):
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1051, in query
    raise NXDOMAIN(qnames=qnames_to_try, responses=nxdomain_responses)
dns.resolver.NXDOMAIN: None of DNS query names exist: 1.2.3.4., 1.2.3.4.dns.suffix.
```

Possibly because of missing PTR record?

It needs to be okay to have no records returned.

**Comment by codingo** [comment]
Agree on PTR record being the likely cause. I think we can put an exception handle in here to continue gracefully and provide some feedback whilst doing so.
